//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the build system.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Reflection;
using System.Runtime.InteropServices;

[assembly: ComVisible(false)]
[assembly: AssemblyTitle("Agdur")]
[assembly: AssemblyDescription("Agdur is a simple micro-benchmarking library for the .NET framework.")]
[assembly: AssemblyProduct("Agdur")]
[assembly: AssemblyCopyright("Copyright (c) Mattias Rydengren 2013")]
[assembly: AssemblyVersion("1.0")]
[assembly: AssemblyInformationalVersion("1.0")]
[assembly: AssemblyFileVersion("1.0")]
[assembly: AssemblyDelaySign(false)]
